In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import copy
%matplotlib inline
from sklearn import preprocessing

In [2]:
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus']=False

In [3]:
trade201904 = pd.read_csv("D:/프로그래밍/2020.9.금융빅데이터/비씨카드/거래내역_201904.csv", sep=",", encoding="CP949")
trade201905 = pd.read_csv("D:/프로그래밍/2020.9.금융빅데이터/비씨카드/거래내역_201905.csv", sep=",", encoding="CP949")
trade202004 = pd.read_csv("D:/프로그래밍/2020.9.금융빅데이터/비씨카드/거래내역_202004.csv", sep=",", encoding="CP949")
trade202005 = pd.read_csv("D:/프로그래밍/2020.9.금융빅데이터/비씨카드/거래내역_202005.csv", sep=",", encoding="CP949")
trade_jobcode = pd.read_csv("D:/프로그래밍/2020.9.금융빅데이터/비씨카드/업종코드.csv", sep=",", encoding="CP949")
trade_comcode = pd.read_csv("D:/프로그래밍/2020.9.금융빅데이터/비씨카드/공통코드.csv", sep=",", encoding="CP949")

In [4]:
trade201904

기준일자  가맹점신우편번호  고객신우편번호    생년  연령대코드 성별코드  매출구분코드  가맹점업종코드  \
0        20190401      6654    14688  1995     25    M       5     9998   
1        20190401      6654    14688  1998     20    F       5     9998   
2        20190401      6654    14697  1999     20    M       5     9998   
3        20190401      6654    14699  1960     60    F       5     9998   
4        20190401      6654    14699  1990     30    F       5     9998   
...           ...       ...      ...   ...    ...  ...     ...      ...   
1048570  20190416     52829    52829  1968     50    M       9     4020   
1048571  20190416     52831    52831  1979     40    F       5     4010   
1048572  20190416     52831    52831  1981     35    M       5     4010   
1048573  20190416     52853    52853  1988     30    F       9     5123   
1048574  20190416     52855    52855  1985     30    F       9     4010   

         할부개월수    매출금액  
0          NaN  128180  
1          NaN   14620  
2          NaN   32000  
3          NaN   17588  
4          NaN   41463  
...        ...     ...  
1048570    NaN   15440  
1048571    NaN    5273  
1048572    NaN    9707  
1048573    NaN  228333  
1048574    NaN   11877  

[1048575 rows x 10 columns]

In [5]:
print(trade201904.duplicated().sum())
print(trade201905.duplicated().sum())
print(trade202004.duplicated().sum())
print(trade202005.duplicated().sum())

194001
200267
0
0


In [6]:
trade_jobcode

업종코드          업종명
0    3302        L P G
1    1002        1급 호텔
2    1001        특급 호텔
3    1003        2급 호텔
4    1010           콘도
..    ...          ...
341  9993     외국인전용가맹점
342  9995      비씨카드정산용
343  9996  비씨카드정산용(할인)
344  9998        기타전문점
345  9999         기타업종

[346 rows x 2 columns]

In [7]:
trade_comcode

코드ID  세부코드ID      코드명     코드값       코드설명내용 키워드명  변경구분
0     CC13       0   매출구분코드       3           선불  NaN   NaN
1     CC13       0   매출구분코드       4        DEBIT  NaN   NaN
2     CC13       0   매출구분코드       5          일시불  NaN   NaN
3     CC13       0   매출구분코드       6        현금서비스  NaN   NaN
4     CC13       0   매출구분코드       7         회전결제  NaN   NaN
...    ...     ...      ...     ...          ...  ...   ...
3832  CC12       3  소분류업종코드  V18B04        시도군구청  NaN   NaN
3833  CC12       3  소분류업종코드  V18B05       읍면동사무소  NaN   NaN
3834  CC12       3  소분류업종코드  V18B07      운전면허시험장  NaN   NaN
3835  CC12       3  소분류업종코드  V18B08         마을회관  NaN   NaN
3836  CC01       0     센터코드   BBP20  한국금융솔루션컨소시엄  NaN   NaN

[3837 rows x 7 columns]

In [8]:
trade_jobcode.loc[(trade_jobcode.업종코드==4010)]

업종코드    업종명
81  4010  편 의 점

In [9]:
trade_2019 = pd.concat([trade201904,trade201905])
trade_2019 = trade_2019.reset_index(drop=True)
trade_2020 = pd.concat([trade202004,trade202005])
trade_2020 = trade_2020.reset_index(drop=True)

In [10]:
trade_2019

기준일자  가맹점신우편번호  고객신우편번호    생년  연령대코드 성별코드  매출구분코드  가맹점업종코드  \
0        20190401      6654    14688  1995     25    M       5     9998   
1        20190401      6654    14688  1998     20    F       5     9998   
2        20190401      6654    14697  1999     20    M       5     9998   
3        20190401      6654    14699  1960     60    F       5     9998   
4        20190401      6654    14699  1990     30    F       5     9998   
...           ...       ...      ...   ...    ...  ...     ...      ...   
2097145  20190514     13606    14619  1976     40    F       5     9153   
2097146  20190514     13606    14620  1964     55    F       5     9153   
2097147  20190514     13606    14621  1958     60    F       5     9153   
2097148  20190514     13606    14633  1994     25    F       5     9153   
2097149  20190514     13606    14636  1991     25    M       5     9153   

         할부개월수    매출금액  
0          NaN  128180  
1          NaN   14620  
2          NaN   32000  
3          NaN   17588  
4          NaN   41463  
...        ...     ...  
2097145    NaN  103467  
2097146    NaN  106097  
2097147    NaN   70097  
2097148    NaN  196167  
2097149    NaN  169020  

[2097150 rows x 10 columns]

In [11]:
print(trade_2019.할부개월수.unique())
print(trade_2020.할부개월수.unique())

[nan  2.  3.  6.]
[0 6 3 2 5]


In [12]:
print(len(trade_2019.할부개월수.loc[(trade_2019.할부개월수.isnull())]))
print(len(trade_2019.할부개월수.loc[(trade_2019.할부개월수 == 2)]))
print(len(trade_2019.할부개월수.loc[(trade_2019.할부개월수 == 3)]))
print(len(trade_2019.할부개월수.loc[(trade_2019.할부개월수 == 6)]))
print("")

print(len(trade_2020.할부개월수.loc[(trade_2020.할부개월수.isnull())]))
print(len(trade_2020.할부개월수.loc[(trade_2020.할부개월수 == 0)]))
print(len(trade_2020.할부개월수.loc[(trade_2020.할부개월수 == 2)]))
print(len(trade_2020.할부개월수.loc[(trade_2020.할부개월수 == 3)]))
print(len(trade_2020.할부개월수.loc[(trade_2020.할부개월수 == 5)]))
print(len(trade_2020.할부개월수.loc[(trade_2020.할부개월수 == 6)]))

# 할부개월수는 nan 또는 0을 제외하고 갯수가 많지않으므로 지우자!

2097105
1
36
8

0
2097070
3
54
1
22


In [13]:
trade_2019 = trade_2019.drop(columns='할부개월수')
trade_2019.isnull().sum()

기준일자        0
가맹점신우편번호    0
고객신우편번호     0
생년          0
연령대코드       0
성별코드        0
매출구분코드      0
가맹점업종코드     0
매출금액        0
dtype: int64

In [14]:
trade_2020 = trade_2020.drop(columns='할부개월수')
trade_2020.isnull().sum()

기준일자        0
가맹점신우편번호    0
고객신우편번호     0
생년          0
연령대코드       0
성별코드        0
매출구분코드      0
가맹점업종코드     0
매출금액        0
dtype: int64

In [15]:
print(trade_2019.duplicated().sum())
print(trade_2020.duplicated().sum())

# ?????? 2019년도 무엇

394268
0


In [16]:
trade_2019.loc[(trade_2019.duplicated())]

기준일자  가맹점신우편번호  고객신우편번호    생년  연령대코드 성별코드  매출구분코드  가맹점업종코드  \
26113    20190401      8393    12104  1977     40    F       5     4076   
26120    20190401      8393    12910  1972     45    M       5     4076   
26121    20190401      8393    12910  1977     40    F       5     4076   
26122    20190401      8393    12910  1981     35    F       5     4076   
26126    20190401      6654    62281  1997     20    M       5     9998   
...           ...       ...      ...   ...    ...  ...     ...      ...   
2097131  20190514     13606    14600  1958     60    F       5     9153   
2097133  20190514     13606    14600  1966     50    M       5     9153   
2097134  20190514     13606    14600  1967     50    F       5     9153   
2097139  20190514     13606    14613  1974     45    M       5     9153   
2097141  20190514     13606    14613  1979     40    M       5     9153   

           매출금액  
26113    187735  
26120    317530  
26121    289392  
26122    283328  
26126     13190  
...         ...  
2097131  101500  
2097133   84990  
2097134   90473  
2097139   35254  
2097141   70040  

[394268 rows x 9 columns]

In [17]:
trade_2019.loc[26113]

기준일자        20190401
가맹점신우편번호        8393
고객신우편번호        12104
생년              1977
연령대코드             40
성별코드               F
매출구분코드             5
가맹점업종코드         4076
매출금액          187735
Name: 26113, dtype: object

In [18]:
trade_2019.loc[(trade_2019.매출금액 == trade_2019.매출금액.loc[26113])]

기준일자  가맹점신우편번호  고객신우편번호    생년  연령대코드 성별코드  매출구분코드  가맹점업종코드    매출금액
21010  20190401      8393    12104  1977     40    F       5     4076  187735
26113  20190401      8393    12104  1977     40    F       5     4076  187735

In [19]:
# 중복값이 너무 많지만, 그래도 확실한 중복값으로 보이니 지우자.

trade_2019 = trade_2019.drop_duplicates()
trade_2019 = trade_2019.reset_index(drop=True)
trade_2019

기준일자  가맹점신우편번호  고객신우편번호    생년  연령대코드 성별코드  매출구분코드  가맹점업종코드  \
0        20190401      6654    14688  1995     25    M       5     9998   
1        20190401      6654    14688  1998     20    F       5     9998   
2        20190401      6654    14697  1999     20    M       5     9998   
3        20190401      6654    14699  1960     60    F       5     9998   
4        20190401      6654    14699  1990     30    F       5     9998   
...           ...       ...      ...   ...    ...  ...     ...      ...   
1702877  20190514     13606    14619  1976     40    F       5     9153   
1702878  20190514     13606    14620  1964     55    F       5     9153   
1702879  20190514     13606    14621  1958     60    F       5     9153   
1702880  20190514     13606    14633  1994     25    F       5     9153   
1702881  20190514     13606    14636  1991     25    M       5     9153   

           매출금액  
0        128180  
1         14620  
2         32000  
3         17588  
4         41463  
...         ...  
1702877  103467  
1702878  106097  
1702879   70097  
1702880  196167  
1702881  169020  

[1702882 rows x 9 columns]

In [20]:
print(trade_2019.매출구분코드.unique())
print(trade_2020.매출구분코드.unique())

[5 9 7 8]
[ 5  9  7  8 19 15 18]


In [21]:
print(len(trade_2019.매출구분코드.loc[(trade_2019.매출구분코드 == 5)]))
print(len(trade_2019.매출구분코드.loc[(trade_2019.매출구분코드 == 7)]))
print(len(trade_2019.매출구분코드.loc[(trade_2019.매출구분코드 == 8)]))
print(len(trade_2019.매출구분코드.loc[(trade_2019.매출구분코드 == 9)]))
print("")

print(len(trade_2020.매출구분코드.loc[(trade_2020.매출구분코드 == 5)]))
print(len(trade_2020.매출구분코드.loc[(trade_2020.매출구분코드 == 7)]))
print(len(trade_2020.매출구분코드.loc[(trade_2020.매출구분코드 == 8)]))
print(len(trade_2020.매출구분코드.loc[(trade_2020.매출구분코드 == 9)]))
print(len(trade_2020.매출구분코드.loc[(trade_2020.매출구분코드 == 15)]))
print(len(trade_2020.매출구분코드.loc[(trade_2020.매출구분코드 == 18)]))
print(len(trade_2020.매출구분코드.loc[(trade_2020.매출구분코드 == 19)]))

# 매출구분은 대부분 일시불/즉시불인데.. 알아본 결과
# 일시불=신용카드 즉시 사용하는 개념,
# 즉시불=체크카드 즉시 사용하는 개념인 듯하다.
# 이 컬럼은 분석에 필요할까..?

973933
4330
44
724575

1053007
10031
79
1033944
41
1
47


In [22]:
sex = {"M":1, "F":0}
trade_2019.replace(sex, inplace=True)
trade_2020.replace(sex, inplace=True)
trade_2019

기준일자  가맹점신우편번호  고객신우편번호    생년  연령대코드  성별코드  매출구분코드  가맹점업종코드  \
0        20190401      6654    14688  1995     25     1       5     9998   
1        20190401      6654    14688  1998     20     0       5     9998   
2        20190401      6654    14697  1999     20     1       5     9998   
3        20190401      6654    14699  1960     60     0       5     9998   
4        20190401      6654    14699  1990     30     0       5     9998   
...           ...       ...      ...   ...    ...   ...     ...      ...   
1702877  20190514     13606    14619  1976     40     0       5     9153   
1702878  20190514     13606    14620  1964     55     0       5     9153   
1702879  20190514     13606    14621  1958     60     0       5     9153   
1702880  20190514     13606    14633  1994     25     0       5     9153   
1702881  20190514     13606    14636  1991     25     1       5     9153   

           매출금액  
0        128180  
1         14620  
2         32000  
3         17588  
4         41463  
...         ...  
1702877  103467  
1702878  106097  
1702879   70097  
1702880  196167  
1702881  169020  

[1702882 rows x 9 columns]